GET http://127.0.0.1:5000/users


#####
POST http://127.0.0.1:5000/educate-chat
Content-Type: application/json

{
    "Id" : "04d8bca4-9c52-49aa-a24d-fe13b9ead816",
    "question" : "number of users with views"
}




